### ISSUE TITLE
error retrieving the session catalog

### ISSUE THREAD

**Issue by fmuntean** [michelderooij/Get-EventSession#12]
Getting following error:
Problem retrieving session catalog: The response content cannot be parsed because the Internet Explorer engine is not
available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter
and try again.

**Comment by fmuntean** [comment]
I have appended -UseBasicParsing to all the Invoke-WebRequest in the script and was able to get this script working again.

**Comment by AutomateP** [comment]
I am still getting this issue with Version 3.52, June 1st, 2021. Is there something I am missing?

**Comment by michelderooij** [comment]
No. Are you using a proxy by any chance? Tested on Windows 10/11.
