### ISSUE TITLE
older events not searchable

### ISSUE THREAD

**Issue by tschrist** [michelderooij/Get-EventSession#13]
PS C:\scripts> .\Get-EventSession.ps1 -event Ignite2019
No proxy setting detected, using direct connection
Using download path: C:\Ignite2019
Running self-update of youtube-dl.exe
ERROR: can't find the current version. Please try again later.

ffmpeg.exe located at C:\scripts\ffmpeg.exe
Reading session catalog
**Problem retrieving session catalog:
Network Error (dns_unresolved_hostname)
Your requested host "api-myignite.techcommunity.microsoft.com" could not be resolved by DNS.**
For assistance, contact your network support team.
At C:\scripts\Get-EventSession.ps1:1036 char:13
```
+             Throw ('Problem retrieving session catalog: {0}' -f $erro ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Problem retriev... support team. :String) [], RuntimeException
    + FullyQualifiedErrorId : Problem retrieving session catalog:
```
Network Error (dns_unresolved_hostname)
Your requested host "api-myignite.techcommunity.microsoft.com" could not be resolved by DNS.
For assistance, contact your network support team.

**Comment by tschrist** [comment]
.\Get-EventSession.ps1 -Event Ignite2019 -DownloadFolder F:Ignite2019 -Format bestvideo+bestaudio -NoRepeats -Language english

Problem retrieving session catalog: **The remote server returned an error: (503) Server Unavailable.**
At C:\Scripts\Get-EventSession.ps1:1087 char:13
+             Throw ('Problem retrieving session catalog: {0}' -f $erro ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Problem retriev...er Unavailable.:String) [], RuntimeException
    + FullyQualifiedErrorId : Problem retrieving session catalog: The remote server returned an error: (503) Server Un
   available.

noticed a change in the script between Ignite2020 and Ignite2019
$Event= 'Ignite2020'
            $EventAPIUrl= 'https://**api.myignite**.microsoft.com'

$Event= 'Ignite2019'
			$EventAPIUrl= 'https://**api-myignite.techcommunity**.microsoft.com'

**Comment by michelderooij** [comment]
https://api.myignite.microsoft.com is the new API endpoint for the catalog.
It doesn't seem to support searching older events anymore.
