### ISSUE TITLE
new version unstable, used to work old versions

### ISSUE THREAD

**Issue by Neckross** [michelderooij/Get-EventSession#15]
Amazing script that I rely so much to download PPT files, I've been using old version for a while no problems.
Download new version from GitHub and getting same error "slides decks are not yet available".
Regardless of the event.. tested "Ignite", "Ignite2020", "Ignite2019", "Ignite2018" and also Inspire events but you receive the same error.

Can you please make available to download the old versions of the script until you fix the new one?

![image](https://user-images.githubusercontent.com/12171199/111053274-77e93180-8430-11eb-99e2-4f8d899555dd.png)
![image](https://user-images.githubusercontent.com/12171199/111053288-9b13e100-8430-11eb-9166-2ae7a17368ec.png)
![image](https://user-images.githubusercontent.com/12171199/111053306-ceef0680-8430-11eb-84a3-de4b432135a3.png)

**Comment by michelderooij** [comment]
Over time, API endpoint changes, MS changes catalog, etc. 
Also, old content might become inaccessible. Not a lot to do about that.
On decks, do note contents is not immediately available. Also, some events do not publish decks.
