### ISSUE TITLE
-NoRepeats not working for Build2021

### ISSUE THREAD

**Issue by AaliAlikoski** [michelderooij/Get-EventSession#17]
If I run

`.\Get-EventSession.ps1 -DownloadFolder c:\Material\Build2021 -Event Build2021 -NoVideos -NoRepeats`

I still get all repeat sessions as well. Tried to look at the code and maybe this is where it breaks down, but I am not that familiar with PowerShell to be able to fix it:

```
     If ($NoRepeats) {
        Write-Verbose ('Skipping repeated sessions')
        $SessionsToGet = $SessionsToGet | Where-Object {$_.sessionCode -inotmatch '^*R[1-9]?$' -and $_.sessionCode -inotmatch '^[A-Z]+[0-9]+[B-C]+$'}
    }
```
Edit: already tried replacing 1-3 with 1-9 as it is in the code snippet above, but no help.

**Comment by michelderooij** [comment]
Works, but depends bit on how repeats are "encoded" in the session code.
