### ISSUE TITLE
Ignite2021 no PPT - WARNING: Skipping: Slidedeck unavailable

### ISSUE THREAD

**Issue by tschrist** [michelderooij/Get-EventSession#18]
![image](https://user-images.githubusercontent.com/2255750/125881048-466aa854-2766-423a-af7f-a271e2524d75.png)

maybe wrong file location? or it changed?
$SlidedeckUrl= 'https://medius.studios.ms/video/asset/PPT/IG21-{0}'

**Comment by michelderooij** [comment]
Script tries deck url when provided with Ignite data, or guess the url. That said, decks not always become available and may become available at later time.
