### ISSUE TITLE
Downloaded videos do not have audio

### ISSUE THREAD

**Issue by fmuntean** [michelderooij/Get-EventSession#22]
seems that audio is missing from the downloaded videos for build 2022.
Get the following warning: WARNING: Multiple audio languages available; will try downloading English audio stream
but then no audio is included in the video.

**Comment by fmuntean** [comment]
Looks that session.cache have special characters: "_x000D__x000A_"

**Comment by michelderooij** [comment]
Which session you have this issue with (to repro)?
