### ISSUE TITLE
Inspire2022 works!  but does not work for inspire2021 or inspire2020

### ISSUE THREAD

**Issue by tschrist** [michelderooij/Get-EventSession#23]
**example output:**

_PS C:\Scripts> .\Get-EventSession.ps1

cmdlet Get-EventSession.ps1 at command pipeline position 1
Supply values for the following parameters:
Event: Inspire2020
Using proxy address http://proxy-us.intel.com:911
Using download path: C:\Inspire2020
Running self-update of youtube-dl.exe

ffmpeg.exe located at C:\Scripts\ffmpeg.exe
Reading session catalog
Problem retrieving session catalog: The underlying connection was closed: Could not establish trust relationship for
the SSL/TLS secure channel.
At C:\Scripts\Get-EventSession.ps1:1157 char:13
+             Throw ('Problem retrieving session catalog: {0}' -f $erro ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Problem retriev...secure channel.:String) [], RuntimeException
    + FullyQualifiedErrorId : Problem retrieving session catalog: The underlying connection was closed: Could not esta
   blish trust relationship for the SSL/TLS secure channel._

**Comment by grzglo** [comment]
Same issue here, both on SystemDefault settings and script TLS set (line 560: [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"). 

Issue occurs only for **Ignite** and not for other events.

**Comment by grzglo** [comment]
> Issue occurs only for **Ignite** and not for other events.

"https://api.myignite.microsoft.com/" gives 404.

**Comment by grzglo** [comment]
> "https://api.myignite.microsoft.com/" gives 404.

Correct address is "https://api.ignite.microsoft.com/".

**Comment by michelderooij** [comment]
Modified endpoints for older Ignite and Inspire events
