### ISSUE TITLE
Ignite2022 nothing to download - what am I doing wrong

### ISSUE THREAD

**Issue by paulschnack** [michelderooij/Get-EventSession#26]
Hi, I've used this great script in the past, now trying to download recordings from Ignite 2022. I've entered both Ignite and Ignite2022 at the event prompt, but all I get is this:
![image](https://user-images.githubusercontent.com/32026739/196670047-ee690622-61a4-464c-a4d3-f8ffe82e8a25.png)
What am I doing wrong?

**Comment by tomrune** [comment]
I see that the script was recently updated, but I would try to use this as it works for me at least: 
Get-EventSession.ps1 -Event Ignite -DownloadFolder V:\Ignite2022
(You may also want to download the Ignite2022-Sessions.cache file stored in the script folder. It is created by and maintained by the script, but if something went wrong reading the catalogue it won't expire until 48 hours has passed or you delete that file. It will be recreated next time you run the script).

Also if you are using a proxy there is a parameter to tell the script to use the proxy address.

**Comment by paulschnack** [comment]
Hi Tom, thanks for getting back to me. Yep, all working now. Thank you.
