### ISSUE TITLE
No videos for Build 2020 ?

### ISSUE THREAD

**Issue by fmuntean** [michelderooij/Get-EventSession#3]
Downloaded 0 slide decks and 0 videos.
400 slide decks and 0 videos are not yet available.

Usually was able to download starting second day.

**Comment by haroldvandekamp** [comment]
I had the same issue when I tried to download the Build 2020 slide decks a couple of months ago.

**Comment by michelderooij** [comment]
Download of Build contents works. Do note MS moves stuff around post-event, so I might need some make some adjustments. Anyway, just tested and Build contents can be retrieved.

**Comment by haroldvandekamp** [comment]
@michelderooij  Just tested this with the 3.38 version to download slide decks, but for me, it doesn't work yet.
`.\Get-EventSession.ps1 -novideos -DownloadFolder "C:\Users\MyFolder\Events\Build 2020" -Event "Build" -NoRepeats`

![image](https://user-images.githubusercontent.com/11357196/88526490-471ccf00-cffc-11ea-97b0-3765db48df3e.png)

![image](https://user-images.githubusercontent.com/11357196/88526188-e8575580-cffb-11ea-9eb2-b60fd9fb0687.png)
