### ISSUE TITLE
Unable to download session cache - latest build

### ISSUE THREAD

**Issue by FlattusBlastus** [michelderooij/Get-EventSession#30]
Reading Ignite2022 session catalog
  Â : The term 'Â' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the       spelling of the name, or if a path was included, verify that the path is correct and try again.                         At E:\I\Get-EventSession.ps1:1157 char:1                                                                                + Â            [int32] $remainder = 0                                                                                   + ~
    + CategoryInfo          : ObjectNotFound: (Â:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Â : The term 'Â' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At E:\I\Get-EventSession.ps1:1158 char:1
+ Â
+ ~
    + CategoryInfo          : ObjectNotFound: (Â:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

[ref] cannot be applied to a variable that does not exist.
At E:\I\Get-EventSession.ps1:1159 char:13
+             $PageCount = [System.Math]::DivRem($sessionCount, $web.it ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (remainder:VariablePath) [], RuntimeException
    + FullyQualifiedErrorId : NonExistingVariableReference

Reading information for 2154 sessions
Storing session information
There are 0 sessions matching your criteria.
Background download jobs have finished
Selected 0 sessions out of a total of 0
Downloaded 0 slide decks and 0 videos.
Not (yet) available: 0 slide decks and 0 videos
Skipped 0 slide decks and 0 videos as they were already downloaded.

**Comment by michelderooij** [comment]
Where does that Â come from? Don't see any 'hidden' character in there.
How did you obtain the script file itself, pull or copy/paste from here or something else?

**Comment by FlattusBlastus** [comment]
Downloaded zip from GitHub. Extracted .PS1 to working folder. Executed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by michelderooij** [comment]
ZIp, that old release? (2.x)  Fetch the raw script from here and try again (after unblocking it)
https://raw.githubusercontent.com/michelderooij/Get-EventSession/master/Get-EventSession.ps1

**Comment by FlattusBlastus** [comment]
Grabbed that. Got the zip again too. That weird behavior with the A is
gone. But....

PS E:\I> .\Get-EventSession.ps1 -DownloadFolder E:\I\Ignite2022 -Format
bestvideo+bestaudio -Event Ignite2022 -MaxDownloadJobs 1 -Captions -Subs en
-NoRepeats
No proxy setting detected, using direct connection
Using download path: E:\I\Ignite2022
Running self-update of youtube-dl.exe
Available version: ***@***.***, Current version: ***@***.***
Current Build Hash:
5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date ***@***.***)

ffmpeg.exe located at E:\I\ffmpeg.exe
Session cache file found, reading session information
There are 0 sessions matching your criteria.
Background download jobs have finished
Selected 0 sessions out of a total of 0
Downloaded 0 slide decks and 0 videos.
Not (yet) available: 0 slide decks and 0 videos
Skipped 0 slide decks and 0 videos as they were already downloaded.

**Comment by michelderooij** [comment]
The script caches the session information as retrieving the catalog takes a while. During the previous run - which failed - you are likely left with an empty session cache file. Use the switch -Refresh to force downloading the session information, or throw away the file (Ignite2022-Sessions.cache), and run Get-EventSession again.

**Comment by FlattusBlastus** [comment]
Deleting the cache files looks to be working. Script is functioning as expected.
A question: I notice a lot of the videos are *.mp4.webm. I haven't seen this before in previous years. Is this expected?

**Comment by michelderooij** [comment]
No. Which session from last year's Ignite is having this ?

**Comment by FlattusBlastus** [comment]
Nearly all of them. a couple are *.mp4.mkv.
.\Get-EventSession.ps1 -DownloadFolder E:\I\Ignite -Format bestvideo+bestaudio -Event Ignite -MaxDownloadJobs 1 -Captions -Subs en -NoRepeats

**Comment by FlattusBlastus** [comment]
ls *.webm  | rename-item -newname { $_.basename }

Gets rid of all the .webm extensions in the directory.

**Comment by michelderooij** [comment]
I see, seems specifying subs - adding parameters to download subtitles - seems to trigger that. I'll reopen this.

**Comment by michelderooij** [comment]
Could repro - was a invisible character in the previous line. Fixed in 3.96
