### ISSUE TITLE
Update .PARAMETER Event

### ISSUE THREAD

**Issue by FlattusBlastus** [michelderooij/Get-EventSession#32]
.PARAMETER Event
    Specify what event to download sessions for. 
    Options are:
    - Ignite                  : Ignite events (current)
    - Ignite2022,Ignite2021   : Ignite contents from that year/time
    - Inspire                 : Inspire contents (current)
    - Inspire2022,Inspire2021 : Inspire contents from that year <-Should read Inspire2023,Inspire2022
    - Build                   : Build contents (current)
    - Build2023,Build2022     : Build contents from that year
    - MEC                     : MEC contents

**Comment by michelderooij** [comment]
Updated
