### ISSUE TITLE
Not an issue - just a question - PowerPoint decks from Ignite 2023?

### ISSUE THREAD

**Issue by paulschnack** [michelderooij/Get-EventSession#33]
Love this script, have used it for years, thank you for creating it. 

Just downloaded 335 sessions from Ignite 2023, but every PPTX it said there was "problem downloading slidedeck". Are they not sharing the decks anylonger? (They're not available to download on any of the session web pages I've seen).

**Comment by paulschnack** [comment]
Sorry, scratch that, just ran the script again, and it's grabbing some decks.

**Comment by ByteBrewerJB** [comment]
It does not work for me, 0 pptx downloads at the moment

**Comment by michelderooij** [comment]
Decks were published for some sessions at Ignite 2023.
