### ISSUE TITLE
The script doesnt like @

### ISSUE THREAD

**Issue by FlattusBlastus** [michelderooij/Get-EventSession#34]
Get-ChildItem: D:\I\Get-EventSession.ps1:748
Line |
 748 |  …                        $FileObj= Get-ChildItem -LiteralPath $job.file
     |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path '\\?\D:\I\Ignite_2023\StudioFP218-Gain a overview of operating Oracle Database@Azure in
     | Azure.vtt' because it does not exist.
InvalidOperation: D:\I\Get-EventSession.ps1:749
Line |
 749 |  …                  $FileObj.CreationTime= Get-Date -Date $job.Timestamp
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'CreationTime' cannot be found on this object. Verify that the property exists and can be set.
InvalidOperation: D:\I\Get-EventSession.ps1:750
Line |
 750 |  …                 $FileObj.LastWriteTime= Get-Date -Date $job.Timestamp
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'LastWriteTime' cannot be found on this object. Verify that the property exists and can be set.

**Comment by michelderooij** [comment]
Sorry, cannot repro
`Downloaded \\?\S:\20231115 Ignite\StudioFP218-Gain a overview of operating Oracle Database@Azure in Azure.vtt
VERBOSE: Applying timestamp 11/16/2023 6:34 PM to \\?\S:\20231115 Ignite\StudioFP218-Gain a overview of operating Oracle Database@Azure in Azure.vtt`
