### ISSUE TITLE
-Format 'bestvideo+bestaudio' does not work

### ISSUE THREAD

**Issue by mikaseitsonen** [michelderooij/Get-EventSession#37]
I successfully downloaded some 140 mp4 files wo -Format parameter. With parameter shown in title, no videos are downloaded

**Comment by mikaseitsonen** [comment]
Downloading high quality mp4 files started working after removing Ignite2024-Sessions.cache

**Comment by michelderooij** [comment]
The (direct) urls for video links or on demand video links were only added after a while. Depending on where the video stream is published, different video filtering options work (or not). FWIW, I always use:
bestvideo[height=720]+bestaudio,bestvideo[height=540]+bestaudio,bestvideo[height=1080]+bestaudio,bestvideo+bestaudio
p720 keeps the text on presented slides or code readable, while not resulting in too massive files.
