### ISSUE TITLE
Downloading the content with the -novideos is not working as expected

### ISSUE THREAD

**Issue by rafnijs** [michelderooij/Get-EventSession#38]
Downloading the content with the -novideos is not working as expected:

PS C:\Source\Get-EventSession> notepad.exe .\Get-EventSession.ps1
PS C:\Source\Get-EventSession> .\Get-EventSession.ps1 -event Ignite -DownloadFolder c:\ignite -NoVideos
No proxy setting detected, using direct connection
Using download path: c:\ignite
Will skip downloading videos
Session cache file found, reading session information
There are 923 sessions matching your criteria.
Processing info session BRK100-Azure OpenAI- the latest innovation for AI powered business value from 11/19/2024 2:30 PM [en-US]
Processing info session BRK101-AI customization- Fine-tuning Azure OpenAI Service models from 11/20/2024 12:00 PM [en-US]
Processing info session BRK102-Introducing Azure AI Foundry Agent Service to scale your AI agents from 11/19/2024 5:00 PM [en-US]
WARNING: Removing BRK100 placeholder file \\?\c:\ignite\BRK100-Azure OpenAI- the latest innovation for AI powered business value.pptx
Problem downloading slidedeck BRK100 Azure OpenAI: the latest innovation for AI powered business value
Processing info session BRK103-Azure AI Foundry unlocking the AI revolution from 11/19/2024 12:30 PM [en-US]
WARNING: Removing BRK101 placeholder file \\?\c:\ignite\BRK101-AI customization- Fine-tuning Azure OpenAI Service models.pptx
Problem downloading slidedeck BRK101 AI customization: Fine-tuning  Azure OpenAI Service models
Processing info session BRK104-How AT&T delivers RAG at scale from 11/20/2024 4:45 PM [en-US]
WARNING: Removing BRK102 placeholder file \\?\c:\ignite\BRK102-Introducing Azure AI Foundry Agent Service to scale your AI agents.pptx
Problem downloading slidedeck BRK102 Introducing Azure AI Foundry Agent Service to scale your AI agents
TERMINATING

Probably the PPTX content is restricted.

**Comment by michelderooij** [comment]
The slidedecks only became available this Saturday; the "error" is a message in the sense it cannot fetch slidedecks, or - in this case - Microsoft puts up placeholder decks which I can download, but then look at the size to determine they are a placeholder after which the placeholder file is removed.
