### ISSUE TITLE
Download Transcript File for Ignite 2024

### ISSUE THREAD

**Issue by bmkaiser** [michelderooij/Get-EventSession#39]
I'm so glad to have found your project! Can you add support for downloading the audio transcript files? These can then be used to help with searching for content within the video and also be used alongside the videos.

**Comment by bmkaiser** [comment]
Nevermind! I overlooked the `-Subs` parameter

**Comment by bmkaiser** [comment]
I tried using `-Subs 'en'` but didn't find that it worked. I think this is because the transcripts file on the session is actually a txt file that's been auto-generated. Can the `-Subs` parameter be updated to work with the transcript files?

**Comment by michelderooij** [comment]
Transcripts depend a lot on the source. Sometimes they put content on YouTube, which has a different selection mechanism compared to Stream for example. I use -Caption for this stream source, which downloads the transcript in VTT format. This can be used as an external subs file using VLC Player for example. When I have some time I will test/verify that mechanism again for other languages, as you can also fetch the audio stream in various languages as well.

**Comment by bmkaiser** [comment]
Thanks, so much! Don't know how I found the `-Subs` parameter, but managed to overlook the `-Captions` parameter. That works great!
