### ISSUE TITLE
Inspire slide decks need to be downloaded as pdf files instead of pptx files

### ISSUE THREAD

**Issue by haroldvandekamp** [michelderooij/Get-EventSession#4]
Thank you for adding support for downloading the Inspire 2020 slide decks @michelderooij .

When I download the slide decks of Inspire using version 3.38 of the script, they are saved as pptx files and seem to be corrupt. However, when I renamed a couple of them to the pdf extension, they open without an issue. Can you fix this?

**Comment by michelderooij** [comment]
Added content-type detection in 3.38

**Comment by haroldvandekamp** [comment]
Thanks for the quick fix @michelderooij . It works now!
