### ISSUE TITLE
relatedResources Not Populating for Ignite 2024

### ISSUE THREAD

**Issue by bmkaiser** [michelderooij/Get-EventSession#41]
I'm not seeing the related resources being populated for Ignite 2024 sessions. I would assume this should pull in the Related Sessions content that is displayed with an update. Below is an example for BRK100.

```powershell
> & .\Get-EventSession.ps1 -Event 'Ignite2024' -InfoOnly -ScheduleCode 'BRK100' | Select relatedResources
No proxy setting detected, using direct connection
Session cache file found, reading session information

relatedResources
----------------
{}
```

Here is a screenshot from the session page that includes the related sessions for BRK100:

![image](https://github.com/user-attachments/assets/f95dbcec-eda4-4337-ad74-2b4810853c84)

**Comment by bmkaiser** [comment]
I do see that the `relatedSessionIds` property populates, but it only has one item instead of a list:

```powershelll
> & .\Get-EventSession.ps1 -Event 'Ignite2024' -InfoOnly -ScheduleCode 'BRK100' | Select relatedSessionIds
No proxy setting detected, using direct connection
Session cache file found, reading session information

relatedSessionIds
-----------------
{6cd1fa6c-9312-410f-be9b-0c5c7c120bfc}
```

**Comment by bmkaiser** [comment]
This may not be so much a problem with the script as it is a problem with the API. It seems that many sessions don't include related sessions (or only a couple) as part of their API response.

**Comment by michelderooij** [comment]
As Brian mentioned, relatedSessionIds contains Id's of related sessions, but is minimal. 
I assume the "related sessions" shown in the portal is a generated suggestion list, which might use these id's, but other content as well.
