### ISSUE TITLE
video quality really bad

### ISSUE THREAD

**Issue by rvdouderaa** [michelderooij/Get-EventSession#6]
The quality of the videos downloaded is really bad.. I can't read the slides.

**Comment by tschrist** [comment]
you may want to try -Format 136 or 137 or 22(default) to make the quality better

YouTube
    =======
    For YouTube videos, you can use the following formats:
    160          mp4        256x144    DASH video  108k , avc1.4d400b, 30fps, video only
    133          mp4        426x240    DASH video  242k , avc1.4d400c, 30fps, video only
    134          mp4        640x360    DASH video  305k , avc1.4d401e, 30fps, video only
    135          mp4        854x480    DASH video 1155k , avc1.4d4014, 30fps, video only
    136          mp4        1280x720   DASH video 2310k , avc1.4d4016, 30fps, video only
    137          mp4        1920x1080  DASH video 2495k , avc1.640028, 30fps, video only
    18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
    22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best, default)

**Comment by rvdouderaa** [comment]
136, 137, 22 all are not available

**Comment by raskeland** [comment]
Hi, please try this:
-format "bestvideo+bestaudio"

It work for me.

**Comment by rvdouderaa** [comment]
Yes, worked for me too. Thanks!
