### ISSUE TITLE
pptx not available for Ignite2020?

### ISSUE THREAD

**Issue by tschrist** [michelderooij/Get-EventSession#7]
getting MP4s but no PPTx - not yet released? or is the script hunting in the wrong spots?

**Comment by vrykodee** [comment]
> 
> 
> getting MP4s but no PPTx - not yet released? or is the script hunting in the wrong spots?

I have the same experience & question!  :-)

**Comment by nicknow** [comment]
I've spot checked a number of the presentations on the Ignite.Microsoft.com site and none are presenting links to download the presentation (PPTX) files. Those may not come for a few days/weeks, not really sure. The script is working the same for 2020 as it did for 2019 and it worked for 2019 (still does work for 2019 PPTX files.)

**Comment by michelderooij** [comment]
PDFs are published now (not for all sessions). Might need re-run in few days to see if more decks are published.
