### ISSUE TITLE
Problem Downloading Multiple Videos with Unsupported URL

### ISSUE THREAD

**Issue by Centranix** [michelderooij/Get-EventSession#8]
I noticed the following error appearing for several videos. The URL that is provided as part of the error message is valid when placed in a Web Browser.

Problem downloading DB117 Unlock cost savings and maximize value with Azure Infrastructure: ERROR: Unsupported URL:

**Comment by Atreidae** [comment]
Adding a little more info here, this isn't an error with @michelderooij 's code. But a limitation of Youtube-dl 

To replicate grab an error message and try parsing the URL to youtube-dl


--Get-EventSession Output--
`Problem downloading ATE-DB110 Ask the Expert: Enterprise-grade Kubernetes on Azure: ERROR: Unsupported URL: https://mediuswesteurope1-uat.azurewebsites.net/Embed/video-nc/IG20-ATE-DB110  `           

--Youtube-DL output--
`PS D:\> .\youtube-dl.exe https://mediuswesteurope1-uat.azurewebsites.net/Embed/video-nc/IG20-ATE-DB110
[generic] IG20-ATE-DB110: Requesting header
WARNING: Falling back on generic information extractor.
[generic] IG20-ATE-DB110: Downloading webpage
[generic] IG20-ATE-DB110: Extracting information
ERROR: Unsupported URL: https://mediuswesteurope1-uat.azurewebsites.net/Embed/video-nc/IG20-ATE-DB110`

Unfortunately not a lot we can do to solve this one, other than raise an issue over on the Youtube-DL GitHub.
Thanks anyway.

**Comment by michelderooij** [comment]
Hm, the ATE-DB110 & ATE-DB117 downloads seem to work just fine. Speculation is that contents was still being distributed to the various regions (links point to medius.studios.ms which gets resolved to a regional CDN).
