### ISSUE TITLE
Download based on Solution area - query

### ISSUE THREAD

**Issue by rajurh** [michelderooij/Get-EventSession#9]
I am trying to download content based on Solution area --> Azure --> Application Development and Not able to download using the PowerShell script. Help on this will be much appreciated

Reference of filter from website
![image](https://user-images.githubusercontent.com/15551296/96360724-01dfe780-117c-11eb-96f7-6706c6e22f98.png)

Script Command I am trying to run:
![image](https://user-images.githubusercontent.com/15551296/96360744-44a1bf80-117c-11eb-85a3-2a3802b80d38.png)

I don't want to download specific to Azure Application Development help on this will be much appreciated.

**Comment by michelderooij** [comment]
In processing, the '|' seems to get lost - for now, I suggest using a wildcard, eg. `'*Azure*Application Development*'`
